steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/andreycloudbuild/andrey-images-repo/myapp:v2.0', '.']

# Run tests and deploy
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'europe-west1-docker.pkg.dev/andreycloudbuild/andrey-images-repo/myapp:v2.0', 
         '/bin/sh', '-c', 'npm test && npm run build && npm run deploy']

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'europe-west1-docker.pkg.dev/andreycloudbuild/andrey-images-repo/myapp:v2.0']

options:
  logging: CLOUD_LOGGING_ONLY  # Option 1: Use Cloud Logging only