steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/andreycloudbuild/andrey-images-repo/myapp:v2.0', '.']

# Run tests and deploy
- name: 'gcr.io/cloud-builders/docker'
  secretEnv: ['GITHUB_TOKEN']
  args: [
    'run', 
    'europe-west1-docker.pkg.dev/andreycloudbuild/andrey-images-repo/myapp:v2.0',
    '/bin/sh', '-c', 
    'git config --global user.email "andrey.kirillov.kiev@gmail.com" && 
     git config --global user.name "andrey_kirillov" && 
     npm test && 
     npm run build && 
     git remote set-url origin https://$$GITHUB_TOKEN@github.com/andrey-kirillov/play-momentjs.git &&
     npx gh-pages -d dist'
  ]

availableSecrets:
  secretManager:
    - versionName: projects/405225510239/secrets/github-token/versions/1
      env: 'GITHUB_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY